version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_docker_ngrok_practice
    ports:
      - 5001:5001
    volumes:
      - .:/app
    environment:
      - NA
    command:
      - ["/opt/venv/bin/python", "run.py"]