version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_docker_ngrok_practice
    restart: always
    environment:
      - FLASK_APP=run.py
    volumes:
      - .:/app
    ports:
      - "5001:5001"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - app
