version: '3.12'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_docker_ngrok_practice
    ports:
      - 5001:5001
    environment:
      - NA
    restart: unless-stopped
